name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ query ]

 

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
     
    - name: query
      run: |
       
        while IFS= read -r line || [ -n "$line" ]; do
            # 忽略空行与注释
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                continue
            fi
          
            docker search $line
            
        done < images.txt
