name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - query
  pull_request:
    branches:
      - query

 

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    
     
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: 'query' # 指定要检出的分支名称
        
    - name: query
      run: |
       
        while IFS= read -r line || [ -n "$line" ]; do
            # 忽略空行与注释
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                continue
            fi
            docker search   $line

            docker search  --format "{{.Name}}: {{.StarCount}}: {{.Description}}: {{.Official}}" $line
            
        done < images.txt
